const words = [
  'REACT', 'JAVASCRIPT', 'PROGRAMACAO', 'COMPUTADOR', 'ALGORITMO',
  'DESENVOLVIMENTO', 'INTERFACE', 'APLICATIVO', 'FRAMEWORK', 'BIBLIOTECA',
  'FUNCIONALIDADE', 'COMPONENTE', 'ESTADO', 'PROPRIEDADE', 'HOOK',
  'EFEITO', 'CONTEXTO', 'REDUCER', 'REFERENCIA', 'MEMORIZACAO',
  'OTIMIZACAO', 'RESPONSIVO', 'ACESSIBILIDADE', 'USABILIDADE', 'EXPERIENCIA',
  'NAVEGADOR', 'SERVIDOR', 'DEPLOY', 'PRODUCAO', 'DESEMPENHO'
];

export const getRandomWord = () => {
  return words[Math.floor(Math.random() * words.length)];
};